name = "CENTCOM Aux Mod"
author = "CENTCOM J-4 Team"
prefix = "CC"
mainprefix = "y"

include = [
    "mod.cpp",
    "meta.cpp",
    "LICENSE",
    "logo_co.paa",
]

[properties]
author = "CENTCOM J-4 Team"

[version]
path = "addons/main/script_version.hpp"