/*
    Default Kits

    This is all of the default kits for players when the game loads they will be dynamically added to "default" kits

    Used with permission from Jerry of the 105th
*/

private ["_kit"];

_kit = [[["CC_MA40","TCP_muzzle_snds_762_01","TCP_acc_pointer_lam_MA40_IR","TCP_optic_EVOSJ1",["CC_32Rnd_762x51_Mag_Tracer_Yellow",32],[],""],[],["CC_M6C","TCP_muzzle_snds_127_01","TCP_acc_flashlight_lam_M6C2","",["CC_12Rnd_10x31_NARQ_Mag_Tracer",12],[],"TCP_bipod_handGuard_M6G2_blk"],["CC_U_B_TacShirt_SlimSleeve_Gloves_Bloused_urban",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_IR_Strobe_Item",1],["greenmag_item_speedloader",1],["tsp_flashbang_m84",2,1],["TCP_M21_Smoke",3,1]]],["CC_M43D_ODST_Black_Company",[["VES_TacSpraycan",1],["tsp_lockpick",1],["ACE_EarPlugs",1],["ACE_CableTie",3],["ACE_Flashlight_XL50",1],["MineDetector",1],["TCP_M9R_Frag",2,1],["ACE_DefusalKit",1],["CC_32Rnd_762x51_Mag_Tracer_Yellow",5,32]]],["CC_Rucksack",[["CC_Biofoam_Light",10],["CC_Medigel_Light",10],["ACE_splint",4],["kat_IV_16",3],["CC_adenosine",3],["CC_Morphine",3],["CC_epinephrine",3],["kat_chestSeal",3],["kat_IO_FAST",3],["CC_PolyHemoglobinIV_1000",2],["CC_PolyHemoglobinIV_500",2],["CC_PolyHemoglobinIV_250",2],["ACE_Tourniquet",1],["kat_caffeine",1],["ACE_Painkillers",1],["kat_Pulseoximeter",1],["ACE_EntrenchingTool",1],["CC_32Rnd_762x51_Mag_Tracer_Yellow",5,32],["CC_12Rnd_10x31_NARQ_Mag_Tracer",1,12],["CC_12Rnd_127x30_SAP_Mag_Tracer",2,12]]],"CC_H_ECH55D_Standard_Blue","",["OPTRE_Smartfinder","","","",["Laserbatteries",1],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_STS",""]],[["ace_earplugs",true]]];
["Standard ODST Rifleman",_kit] call ace_arsenal_fnc_addDefaultLoadout;

_kit = [[["CC_LMG_M731","TCP_muzzle_snds_762_01","TCP_acc_carryHandle_M731","TCP_optic_M27RCO",["CC_100rnd_Mag_Tracer_Yellow",100],[],"TCP_bipod_01"],[],["CC_M6C","TCP_muzzle_snds_127_01","TCP_acc_flashlight_lam_M6C2","",["CC_12Rnd_10x31_NARQ_Mag_Tracer",12],[],"TCP_bipod_handGuard_M6G2_blk"],["CC_U_B_TacShirt_SlimSleeve_Gloves_Bloused_urban",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_IR_Strobe_Item",1],["greenmag_item_speedloader",1],["tsp_flashbang_m84",2,1],["TCP_M21_Smoke",3,1]]],["CC_M43D_ODST_Black_Company",[["VES_TacSpraycan",1],["tsp_lockpick",1],["ACE_EarPlugs",1],["ACE_CableTie",3],["ACE_Flashlight_XL50",1],["MineDetector",1],["TCP_M9R_Frag",2,1],["ACE_DefusalKit",1],["CC_100rnd_Mag_Tracer_Yellow",2,100]]],["CC_Rucksack_hev",[["CC_Biofoam_Light",10],["CC_Medigel_Light",10],["ACE_splint",4],["kat_IV_16",3],["CC_adenosine",3],["CC_Morphine",3],["CC_epinephrine",3],["kat_chestSeal",3],["kat_IO_FAST",3],["CC_PolyHemoglobinIV_1000",2],["CC_PolyHemoglobinIV_500",2],["CC_PolyHemoglobinIV_250",2],["ACE_Tourniquet",1],["kat_caffeine",1],["ACE_Painkillers",1],["kat_Pulseoximeter",1],["ACE_EntrenchingTool",1],["CC_100rnd_Mag_Tracer_Yellow",3,100],["CC_12Rnd_10x31_NARQ_Mag_Tracer",1,12],["CC_12Rnd_127x30_SAP_Mag_Tracer",2,12],["ACE_Tripod",2]]],"CC_H_ECH55D_Standard_Blue","",["OPTRE_Smartfinder","","","",["Laserbatteries",1],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_STS",""]],[["ace_earplugs",true]]];
["Standard ODST Autorifleman",_kit] call ace_arsenal_fnc_addDefaultLoadout;

_kit = [[["CC_MA40","TCP_muzzle_snds_762_01","TCP_acc_pointer_lam_MA40_IR","TCP_optic_EVOSJ1",["CC_32Rnd_762x51_Mag_Tracer_Yellow",32],[],""],["CC_M41_SSR","","","",["CC_HEAT",2],[],""],["CC_M6C","TCP_muzzle_snds_127_01","TCP_acc_flashlight_lam_M6C2","",["CC_12Rnd_10x31_NARQ_Mag_Tracer",12],[],"TCP_bipod_handGuard_M6G2_blk"],["CC_U_B_TacShirt_SlimSleeve_Gloves_Bloused_urban",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_IR_Strobe_Item",1],["greenmag_item_speedloader",1],["tsp_flashbang_m84",2,1],["TCP_M21_Smoke",3,1]]],["CC_M43D_ODST_Black_Company",[["VES_TacSpraycan",1],["tsp_lockpick",1],["ACE_EarPlugs",1],["ACE_CableTie",3],["ACE_Flashlight_XL50",1],["MineDetector",1],["TCP_M9R_Frag",2,1],["ACE_DefusalKit",1],["CC_32Rnd_762x51_Mag_Tracer_Yellow",5,32]]],["CC_Rucksack_hev",[["CC_Biofoam_Light",10],["CC_Medigel_Light",10],["ACE_splint",4],["kat_IV_16",3],["CC_adenosine",3],["CC_Morphine",3],["CC_epinephrine",3],["kat_chestSeal",3],["kat_IO_FAST",3],["CC_PolyHemoglobinIV_1000",2],["CC_PolyHemoglobinIV_500",2],["CC_PolyHemoglobinIV_250",2],["ACE_Tourniquet",1],["kat_caffeine",1],["ACE_Painkillers",1],["kat_Pulseoximeter",1],["ACE_EntrenchingTool",1],["CC_32Rnd_762x51_Mag_Tracer_Yellow",5,32],["CC_12Rnd_10x31_NARQ_Mag_Tracer",1,12],["CC_12Rnd_127x30_SAP_Mag_Tracer",2,12],["CC_HEAT",1,1],["CC_HEAA",1,1]]],"CC_H_ECH55D_Standard_Blue","",["OPTRE_Smartfinder","","","",["Laserbatteries",1],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_STS",""]],[["ace_earplugs",true]]];
["Standard ODST AT",_kit] call ace_arsenal_fnc_addDefaultLoadout;

_kit = [[["CC_M392_DMR","TCP_muzzle_snds_762_01","TCP_acc_flashlight_M392","NSWep_BR55M1A2LR_Optic",["CC_15Rnd_762x51_Mag_Tracer_Yellow",15],[],""],[],["CC_M6C","TCP_muzzle_snds_127_01","TCP_acc_flashlight_lam_M6C2","",["CC_12Rnd_10x31_NARQ_Mag_Tracer",12],[],"TCP_bipod_handGuard_M6G2_blk"],["CC_U_B_TacShirt_SlimSleeve_Gloves_Bloused_urban",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_IR_Strobe_Item",1],["greenmag_item_speedloader",1],["tsp_flashbang_m84",2,1],["TCP_M21_Smoke",3,1]]],["CC_M43D_ODST_Black_Company",[["VES_TacSpraycan",1],["tsp_lockpick",1],["ACE_EarPlugs",1],["ACE_CableTie",3],["ACE_Flashlight_XL50",1],["MineDetector",1],["TCP_M9R_Frag",2,1],["ACE_DefusalKit",1],["CC_15Rnd_762x51_Mag_Tracer_Yellow",5,15]]],["CC_Rucksack",[["CC_Biofoam_Light",10],["CC_Medigel_Light",10],["ACE_splint",4],["kat_IV_16",3],["CC_adenosine",3],["CC_Morphine",3],["CC_epinephrine",3],["kat_chestSeal",3],["kat_IO_FAST",3],["CC_PolyHemoglobinIV_1000",2],["CC_PolyHemoglobinIV_500",2],["CC_PolyHemoglobinIV_250",2],["ACE_Tourniquet",1],["kat_caffeine",1],["ACE_Painkillers",1],["kat_Pulseoximeter",1],["ACE_EntrenchingTool",1],["CC_15Rnd_762x51_Mag_Tracer_Yellow",5,15],["CC_12Rnd_10x31_NARQ_Mag_Tracer",1,12],["CC_12Rnd_127x30_SAP_Mag_Tracer",2,12]]],"CC_H_ECH55D_Standard_Blue","",["OPTRE_Smartfinder","","","",["Laserbatteries",1],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_STS",""]],[["ace_earplugs",true]]];
["Standard ODST Marksman",_kit] call ace_arsenal_fnc_addDefaultLoadout;

_kit = [[["CC_MA40","TCP_muzzle_snds_762_01","TCP_acc_pointer_lam_MA40_IR","TCP_optic_EVOSJ1",["CC_32Rnd_762x51_Mag_Tracer_Yellow",32],[],""],[],["CC_M6C","TCP_muzzle_snds_127_01","TCP_acc_flashlight_lam_M6C2","",["CC_12Rnd_10x31_NARQ_Mag_Tracer",12],[],"TCP_bipod_handGuard_M6G2_blk"],["CC_U_B_TacShirt_SlimSleeve_Gloves_Bloused_urban",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_IR_Strobe_Item",1],["greenmag_item_speedloader",1],["tsp_flashbang_m84",2,1],["TCP_M21_Smoke",3,1]]],["CC_M43D_ODST_Black_Company",[["VES_TacSpraycan",1],["tsp_lockpick",1],["ACE_EarPlugs",1],["ACE_CableTie",3],["ACE_Flashlight_XL50",1],["MineDetector",1],["TCP_M9R_Frag",2,1],["ACE_DefusalKit",1],["CC_32Rnd_762x51_Mag_Tracer_Yellow",5,32]]],["CC_Rucksack_med",[["ACE_surgicalKit",1],["kat_X_AED",1],["kat_accuvac",1],["kat_txa",3],["kat_larynx",5],["kat_guedel",5],["CC_Medigel",5],["CC_Biofoam",5],["CC_Biofoam_Light",20],["CC_Medigel_Light",20],["ACE_splint",12],["kat_IV_16",10],["CC_adenosine",10],["CC_Morphine",10],["CC_epinephrine",10],["kat_chestSeal",10],["kat_IO_FAST",10],["CC_PolyHemoglobinIV_1000",4],["CC_PolyHemoglobinIV_500",8],["CC_PolyHemoglobinIV_250",5],["ACE_Tourniquet",1],["kat_caffeine",3],["kat_Pulseoximeter",1],["ACE_EntrenchingTool",1],["CC_32Rnd_762x51_Mag_Tracer_Yellow",2,32],["CC_12Rnd_10x31_NARQ_Mag_Tracer",1,12],["CC_12Rnd_127x30_SAP_Mag_Tracer",2,12]]],"CC_H_ECH55D_Standard_Red","",["OPTRE_Smartfinder","","","",["Laserbatteries",1],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_STS",""]],[["ace_earplugs",true]]];
["Standard ODST SORC",_kit] call ace_arsenal_fnc_addDefaultLoadout;

_kit = [[["CC_MA40GL","TCP_muzzle_snds_762_01","TCP_acc_pointer_lam_MA40_IR","TCP_optic_EVOSJ1",["CC_32Rnd_762x51_Mag_Tracer_Yellow",32],["TCP_1Rnd_40_Shell_HE",1],""],[],["CC_M6C","TCP_muzzle_snds_127_01","TCP_acc_flashlight_lam_M6C2","",["CC_12Rnd_10x31_NARQ_Mag_Tracer",12],[],"TCP_bipod_handGuard_M6G2_blk"],["CC_U_B_TacShirt_SlimSleeve_Gloves_Bloused_urban",[["ItemAndroid",1],["ItemcTabHCam",1],["ACE_IR_Strobe_Item",1],["greenmag_item_speedloader",1],["tsp_flashbang_m84",2,1],["TCP_M21_Smoke",3,1]]],["CC_M43D_ODST_Black_Company",[["VES_TacSpraycan",1],["tsp_lockpick",1],["ACE_EarPlugs",1],["ACE_CableTie",3],["ACE_Flashlight_XL50",1],["MineDetector",1],["TCP_M9R_Frag",2,1],["ACE_DefusalKit",1],["CC_32Rnd_762x51_Mag_Tracer_Yellow",5,32],["TCP_1Rnd_40_Shell_HE",5,1]]],["CC_Rucksack",[["CC_Biofoam_Light",10],["CC_Medigel_Light",10],["ACE_splint",4],["kat_IV_16",3],["CC_adenosine",3],["CC_Morphine",3],["CC_epinephrine",3],["kat_chestSeal",3],["kat_IO_FAST",3],["CC_PolyHemoglobinIV_1000",2],["CC_PolyHemoglobinIV_500",2],["CC_PolyHemoglobinIV_250",2],["ACE_Tourniquet",1],["kat_caffeine",1],["ACE_Painkillers",1],["kat_Pulseoximeter",1],["ACE_EntrenchingTool",1],["CC_32Rnd_762x51_Mag_Tracer_Yellow",5,32],["CC_12Rnd_10x31_NARQ_Mag_Tracer",1,12],["CC_12Rnd_127x30_SAP_Mag_Tracer",2,12],["TCP_1Rnd_40_Shell_HE",10,1],["TCP_1Rnd_40_Shell_Smoke_White",5,1],["TCP_1Rnd_40_Shell_Smoke_Red",3,1],["TCP_1Rnd_40_Shell_Smoke_Blue",3,1],["TCP_1Rnd_40_Shell_Signal_Green",2,1],["TCP_1Rnd_40_Shell_Signal_Red",2,1],["TCP_1Rnd_40_Shell_Signal_Yellow",2,1]]],"CC_H_ECH55D_Standard_Blue","",["OPTRE_Smartfinder","","","",["Laserbatteries",1],[],""],["ItemMap","","TFAR_anprc152","ItemCompass","KAT_STS",""]],[["ace_earplugs",true]]];
["Standard ODST Grenadier",_kit] call ace_arsenal_fnc_addDefaultLoadout;

// Aviation Default Kits

_kit = [[["CC_MA5K","","","OPTRE_Evo_Sight_Riser",["CC_60Rnd_762x51_Mag_Tracer_Yellow",60],[],""],[],["CC_M8_FlareGun","","","",["TCP_1Rnd_12Gauge_Shell_Signal_Green",1],[],""],["CC_U_B_TacShirt_SlimSleeve_Gloves_Bloused_black",[["ACE_Splint",4],["ACE_tourniquet",1],["kat_chestSeal",3],["kat_IO_Fast",3],["kat_guedel",3],["kat_larynx",3],["ACE_painkillers",2]]],["CC_M43A_Aviator_Black",[["ACE_IR_Strobe_Item",1],["ItemcTabHCam",1],["ACE_earplugs",1],["ACE_cabletie",10],["ACE_mapTools",1],["ACE_flashlight_XL50",1]]],["B_Parachute",[]],"CC_VX19_Helmet_Base","",["","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","kat_katmin",""]],[["ace_earplugs",true]]];
["Standard VC-713 Aviator",_kit] call ace_arsenal_fnc_addDefaultLoadout;
